# Generated by Django 3.1.5 on 2021-01-11 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamelist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_av')),
                ('nickname', models.CharField(max_length=18)),
                ('bio', models.TextField(max_length=450)),
                ('fav_game', models.CharField(max_length=20)),
                ('platform_used', models.CharField(max_length=12)),
                ('currently_playing', models.CharField(max_length=20)),
                ('games_in_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelist.games_collection')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelist.games_reviews')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
