# Generated by Django 3.1.5 on 2021-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0003_auto_20210112_1229'),
        ('users', '0002_auto_20210111_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_game_reviews',
            name='review',
        ),
        migrations.RemoveField(
            model_name='user_game_reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='game',
            field=models.ManyToManyField(to='gamelist.Games_Collection'),
        ),
        migrations.AddField(
            model_name='profile',
            name='review',
            field=models.ManyToManyField(to='gamelist.Games_Reviews'),
        ),
        migrations.DeleteModel(
            name='User_Game_Collection',
        ),
        migrations.DeleteModel(
            name='User_Game_Reviews',
        ),
    ]
