# Generated by Django 3.1.5 on 2021-01-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_steam_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='platform_used',
            field=models.CharField(max_length=30),
        ),
    ]
