# Generated by Django 3.1.5 on 2021-01-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0004_auto_20210118_1948'),
        ('users', '0005_auto_20210119_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='game',
        ),
        migrations.CreateModel(
            name='ProfileGamesCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('games_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelist.gamescollection')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
