# Generated by Django 3.1.5 on 2021-01-26 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210124_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilegamescollection',
            name='currently_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilegamescollection',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profilegamescollection',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
