# Generated by Django 3.1.5 on 2021-02-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210202_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='platform_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profilehardware'),
        ),
    ]
