# Generated by Django 3.1.5 on 2021-02-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210202_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hardware',
        ),
        migrations.DeleteModel(
            name='ProfileHardware',
        ),
    ]
