# Generated by Django 3.1.5 on 2021-02-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210202_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='default-bg.jpg', upload_to='profile_bg'),
        ),
    ]
