# Generated by Django 3.1.5 on 2021-02-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210202_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='review',
        ),
    ]
