# Generated by Django 3.1.5 on 2021-02-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210202_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='review',
        ),
    ]
