# Generated by Django 3.1.5 on 2021-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_profile_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='steam_link',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
