# Generated by Django 3.1.5 on 2021-01-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('developer', models.CharField(max_length=12)),
                ('genre', models.CharField(max_length=12)),
                ('platforms', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Games_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=600)),
                ('game_reviewed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gamelist.games_collection')),
            ],
        ),
    ]
