# Generated by Django 3.1.5 on 2021-01-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games_collection',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='game_cover'),
        ),
    ]
