# Generated by Django 3.1.5 on 2021-01-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0002_games_collection_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games_reviews',
            name='game_reviewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelist.games_collection'),
        ),
    ]
