# Generated by Django 3.1.5 on 2021-01-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210112_1229'),
        ('gamelist', '0003_auto_20210112_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games_Collection',
            new_name='GamesCollection',
        ),
        migrations.RenameModel(
            old_name='Games_Reviews',
            new_name='GamesReviews',
        ),
    ]
