# Generated by Django 3.1.5 on 2021-01-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescollection',
            name='belong_to_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamelist.company'),
            preserve_default=False,
        ),
    ]
