# Generated by Django 3.1.5 on 2021-01-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0007_remove_gamescollection_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='gamescollection',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelist.gamegenre'),
        ),
    ]
