# Generated by Django 3.1.5 on 2021-02-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0009_auto_20210202_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescollection',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='game_cover'),
        ),
    ]
