# Generated by Django 3.1.5 on 2021-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0013_auto_20210203_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplatform',
            name='game_platform',
            field=models.CharField(max_length=16),
        ),
    ]
