# Generated by Django 3.1.5 on 2021-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0014_auto_20210203_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescollection',
            name='description',
            field=models.TextField(max_length=450, null=True),
        ),
    ]
