# Generated by Django 3.1.5 on 2021-02-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0015_gamescollection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesreviews',
            name='review_score',
            field=models.IntegerField(null=True),
        ),
    ]
