# Generated by Django 3.1.5 on 2021-02-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0016_gamesreviews_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesreviews',
            name='review_score',
        ),
    ]
