# Generated by Django 3.1.5 on 2021-02-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0017_remove_gamesreviews_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesreviews',
            name='review_score',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
