# Generated by Django 3.1.5 on 2021-02-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0018_gamesreviews_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesreviews',
            name='gameplay_score',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesreviews',
            name='music_score',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesreviews',
            name='story_score',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesreviews',
            name='visual_score',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
