# Generated by Django 3.1.5 on 2021-02-19 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0020_gamesreviews_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescollection',
            name='year_released',
            field=models.IntegerField(default=1999, validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1980)]),
            preserve_default=False,
        ),
    ]
